### ISSUE TITLE
terraform provider phpipam provider intialization fails

### ISSUE THREAD

**Issue by thatsk** [lord-kyron/terraform-provider-phpipam#13]
```YAML
kthakur@node: ~/terraform/vsphere/.terraform/plugins/linux_amd64$ cp /home/kthakur/terraform-provider-phpipam/terraform-provider-phpipam .
kthakur@node: ~/terraform/vsphere/.terraform/plugins/linux_amd64$ ls
lock.json  terraform-provider-null_v2.1.2_x4  terraform-provider-restapi_v1.12.0
phpipam    terraform-provider-phpipam         terraform-provider-vsphere_v1.18.1_x4
```
```YAMl
kthakur@: ~/terraform/vsphere$ terraform init
kthakur@node: ~/terraform/vsphere$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Missing name for resource

  on phpipam.tf line 18, in resource "phpipam_address":
  18: resource "phpipam_address" {

All resource blocks must have 2 labels (type, name).
```
